import Footer from "@/components/footer/page";
import NavbarAdmin from "@/components/navbarAdmin/page";
import SiderbarAdmin from "@/components/siderbarAdmin/page";




import type { Metadata } from "next";
import { Children } from "react";

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className="flex">
                <SiderbarAdmin />
                <NavbarAdmin>   {children}</NavbarAdmin>
            </div>

            <Footer />

        </>

    );
}