import UserHeader from "@/components/header/UserHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <UserHeader />
            {children}
        </>



    );
}
