import Footer from "@/components/footer/page";
import GuestHeader from "@/components/header/GuestHeader";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <GuestHeader />
            {children}
            <Footer />
        </>



    );
}
