import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
    title: "Booking Page",
    description: "Generated by create next app",
};

export default function ServiceLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
        </>
    );
}
