import Footer from "@/components/footer/page";
import GuestHeader from "@/components/guestHeader/page";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Booking",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>

            <GuestHeader />

            {children}
            <Footer />





        </>



    );
}
